### ISSUE TITLE
Not all lights in theatre group dim

### ISSUE THREAD

**Issue by paulnd** [sanghviharshit/script.kodi.lifx.ambilight#25]
Hi,

Thanks for an excellent addon.

Paul

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] feedback

* **If the current behavior is a bug, please provide the steps to reproduce**

* **What is the current behavior?**
Not all lights are dimmed intermittently, disabling and then enabling the addon restores the function

* **What is the expected behavior?**
All lights in theatre group should dim

* **What is the motivation / use case for changing the behavior?**

* **Please tell me about your environment:**
    - Version
    - Kodi: 17.6
    - Addon: 1.0.2
  - OS: Android (FireTV v3)
  - Lifx Devices: 3 x LIFX + A60

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, etc.)
```

21:33:53.499 T:367276470528   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'bitstring.CreationError'>
                                            Error Contents: 4078847 is too large an unsigned integer for a bitstring of length 16. The allowed range is [0, 65535].
                                            Traceback (most recent call last):
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/player.py", line 29, in onPlayBackStarted
                                                self.hue_service.state_changed("started", self.duration)
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/service_entry.py", line 189, in state_changed
                                                self.theater_controller.on_playback_start(resume)
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/theater_controller.py", line 40, in on_playback_start
                                                kel=kel,
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lights.py", line 265, in set_state
                                                transition_time=transition_time
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lights.py", line 164, in set_state
                                                self.light.set_color(color, state['transitiontime']*100, rapid=state['rapid'])
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lifxlan/light.py", line 82, in set_color
                                                self.req_with_ack(LightSetColor, {"color": color, "duration": duration})
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lifxlan/device.py", line 485, in req_with_ack
                                                self.req_with_resp(msg_type, Acknowledgement, payload, timeout_secs, max_attempts)
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lifxlan/device.py", line 496, in req_with_resp
                                                msg = msg_type(self.mac_addr, self.source_id, seq_num=0, payload=payload, ack_requested=True, response_requested=False)
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lifxlan/msgtypes.py", line 337, in __init__
                                                super(LightSetColor, self).__init__(MSG_IDS[LightSetColor], target_addr, source_id, seq_num, ack_requested, response_requested)
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lifxlan/message.py", line 43, in __init__
                                                self.packed_message = self.generate_packed_message()
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lifxlan/message.py", line 46, in generate_packed_message
                                                self.payload = self.get_payload()
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lifxlan/msgtypes.py", line 343, in get_payload
                                                color = b"".join(little_endian(bitstring.pack("16", field)) for field in self.color)
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/lifxlan/msgtypes.py", line 343, in <genexpr>
                                                color = b"".join(little_endian(bitstring.pack("16", field)) for field in self.color)
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/bitstring.py", line 4215, in pack
                                                s._append(BitStream._init_with_token(name, length, value))
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/bitstring.py", line 1223, in _init_with_token
                                                b = cls(**{name: int(value), 'length': token_length})
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/bitstring.py", line 4124, in __new__
                                                x._initialise(auto, length, offset, **kwargs)
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/bitstring.py", line 821, in _initialise
                                                init_with_length_only[k](self, v, length)
                                              File "/storage/sdcard1/Android/data/org.xbmc.kodi/files//.kodi/addons/script.kodi.lifx.ambilight/resources/lib/bitstring.py", line 1362, in _setuint
                                                raise CreationError(msg, uint, length, (1 << length) - 1)
                                            CreationError: 4078847 is too large an unsigned integer for a bitstring of length 16. The allowed range is [0, 65535].
                                            -->End of Python script error report<-
```

**Comment by sanghviharshit** [comment]
Can you please turn debug logging on and then reproduce the issue, so I can get information about your current settings and some context when it failed? To record the logs, go to settings wheel -> System settings -> Logging -> Enable Debug Logging and follow the procedure at http://kodi.wiki/view/Log_file/Easy

**Comment by paulnd** [comment]
Here's a link to the log, all lights dim the first time after the addon starts but only one light dims after that.

https://pastebin.com/KWAkRefU

**Comment by sanghviharshit** [comment]
Thanks for the logs, I was able to find the issue and have fixed it in `develop` branch, I will release a new version with the fix soon and Kodi should auto-update to the new version
